---
- hosts: dev
  remote_user: ansible
  become: sudo
  tasks:
    - name: unarchive
      unarchive:
        scr: /opt/apache-tomcat-8.0.32.tar.gz
        dest: /opt/tomcat
        remote_src: yes`
      
      notify:
        - restart tomcat

    - name: Change ownership of Tomcat installation
      file: path=/opt/tomcat/ owner=tomcat group=tomcat state=directory recurse=yes

    - name: Configure Tomcat server
      template: src=server.xml dest=/opt/tomcat/conf/

    - name: Configure Tomcat users
      template: src=tomcat-users.xml dest=/opt/tomcat/conf/

    - name: Install Tomcat SystemD Unit File
      copy: src=tomcat.service dest=/etc/systemd/system/tomcat.service

    - name: Start Tomcat
      systemd:
        name: tomcat
        state: started
        enabled: yes 
        daemon_reload: yes
